require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.lualine"
require "user.cmp"
require "user.lsp"
require "user.markdown"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.vista"
-- require "user.symbols-outline"
